name: royal_prime
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+17

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animation_wrappers: ^3.0.0
  flutter_bloc: ^8.1.3
  flutter_phoenix: ^1.1.1
  shared_preferences: ^2.2.2
  get: ^4.6.5
  http: ^0.13.5
  logger:
  fluttertoast: ^8.2.4
  get_storage: ^2.1.1
  whatsapp: ^2.0.0
  url_launcher: ^6.1.6
  image_picker:
  cached_network_image: ^3.2.2
  socket_io_client: ^2.0.3+1
  #  flutter_locales: ^2.0.2
  intl: ^0.17.0
  pdf: ^3.1.0
  path_provider: ^2.1.1
  #  open_file: ^3.1.0
  printing: ^5.9.3
  dotted_line: ^3.2.2
  google_fonts: ^4.0.4
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.0.6
  equatable: ^2.0.5
  google_nav_bar: ^5.0.6
  omni_datetime_picker: 1.0.2
  dropdown_button2: ^1.9.2
  #  app_settings: ^4.2.0
  #firebase_core: ^2.10.0
  #firebase_messaging: ^14.4.1
  flutter_local_notifications: ^16.2.0
  overlay_support: ^2.1.0
  font_awesome_flutter: ^10.4.0
  data_table_2: ^2.3.11
  #  flutter_typeahead: ^4.4.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  upgrader: ^6.5.0
  mailer: ^6.0.1
  flutter_pos_printer_platform: ^1.1.0
  esc_pos_printer: ^4.1.0
  esc_pos_utils: ^1.1.0
  package_info_plus: ^3.0.3

dependency_overrides:
  intl: ^0.18.0
  #  tablemi.com
#  ping_discover_network: ^0.2.0+1
#  esc_pos_printer: ^4.1.0
#
#  network_tools: ^3.0.0+3
#  pos_printer_manager: ^0.0.5
#
#  printing: ^5.9.3

  # buy_this_app:
  #   git:
  #     url: git@gitlab.com:verbosetech-flutter/buy-this-app-package.git
  #     ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  change_app_package_name: ^1.1.0
#  flutter_launcher_name: ^0.0.1

# Run bottom command in terminal to change the application package name throughout the project
#  flutter pub run change_app_package_name:main com.new.package.name

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/bizmodo_icons/royalicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/bizmodo_icons/royalicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/bizmodo_icons/royalicon.png"
#  flutter pub run flutter_launcher_icons:main

flutter_launcher_name:
  name: "Foodies"
#  flutter pub run flutter_launcher_name:main

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/ItemCategory/
    - assets/
    - assets/food items/
    - assets/bizmodo_icons/

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/ProductSans-Bold.ttf
        - asset: assets/fonts/ProductSans-Regular.ttf

